version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my-go-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - ./.env
    depends_on:
      - db
    entrypoint: ["/wait.sh", "db", "${DB_PORT}", "/main"]

volumes:
  postgres-data: